=== txss/XML_Project/master.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">



	<xs:element name="master">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="intervenant" />
				<xs:element maxOccurs="unbounded" ref="UE" />
				<xs:element maxOccurs="2" minOccurs="2" ref="parcours" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>




	<xs:element name="UE">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nomUE" type="xs:string" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="ref-intervenant" />
				<xs:element name="nbCreditsUE" type="xs:string" />

				<xs:element name="résumé" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" ref="p" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="plan" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" ref="p" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="lieu_d_enseignement" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice>
							<xs:element ref="Luminy" />
							<xs:element ref="St-Jerôme" />
						</xs:choice>
					</xs:complexType>
				</xs:element>


			</xs:sequence>
			<xs:attribute name="id" use="required" type="xs:ID" />
		</xs:complexType>
	</xs:element>



	<xs:element name="ref-intervenant">
		<xs:complexType>
			<xs:attribute name="ref" use="required" type="xs:IDREF" />
		</xs:complexType>
	</xs:element>





	<xs:element name="Luminy">
		<xs:complexType />
	</xs:element>
	<xs:element name="St-Jerôme">
		<xs:complexType />
	</xs:element>


	<xs:element name="p">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="b" type="xs:string" />
				<xs:element name="i" type="xs:string" />
				<xs:element name="t" type="xs:string" />
				<xs:element ref="p" />



				<xs:element name="ul">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="li" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" ref="p" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="table">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tr" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="td" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" ref="p" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="a" type="xs:string" />
			</xs:choice>
		</xs:complexType>
	</xs:element>



	<xs:element name="intervenant">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nomIntervenant" type="xs:string" />
				<xs:element name="mail" type="xs:string" />
				<xs:element name="siteWeb" minOccurs="0" type="xs:string" />
				<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" use="required" type="xs:ID" />
		</xs:complexType>
	</xs:element>





	<xs:element name="semestre">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="bloc-UE">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nbCreditsBloc" minOccurs="0" type="xs:string" />
							<xs:element maxOccurs="unbounded" ref="refUE" />
						</xs:sequence>
						<xs:attribute name="rôle" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="Obligatoire" />
									<xs:enumeration value="Facultatif" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<xs:element name="refUE">
		<xs:complexType>
			<xs:attribute name="refUE" use="required" type="xs:IDREF" />
		</xs:complexType>
	</xs:element>

	<xs:element name="parcours">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="responsable" minOccurs = "0" type="xs:string" />
				<xs:element name="nomParcours" type="xs:string" />
				<xs:element name="description">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" ref="p" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="débouché" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" ref="p" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="2" maxOccurs="2" ref="semestre" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>



</xs:schema>

=== txss/XML_Project/donnesFinales_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<master xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="master.xsd">
  <intervenant id="IN10388">
    <nom>FAVRE Benoit</nom>
    <mail>benoit.favre@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN12068">
    <nom>HABET Djamal</nom>
    <mail>djamal.habet@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN12316">
    <nom>DEMONGODIN Isabelle</nom>
    <mail>isabel.demongodin@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN12544">
    <nom>BOUCELMA Omar</nom>
    <mail>omar.boucelma@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN12632">
    <nom>OLIVETTI Nicola</nom>
    <mail>nicola.olivetti@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN12834">
    <nom>OUTBIB Rachid</nom>
    <mail>rachid.outbib@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN12969">
    <nom>RENE CHABAROT Lydie</nom>
    <mail>lydie.rene@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN13794">
    <nom>OLIVE Frederic</nom>
    <mail>frederic.olive@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN14758">
    <nom>BROCHE Martine</nom>
    <mail>martine.broche@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN16209">
    <nom>RALAIVOLA Hery Liva</nom>
    <mail>hery-liva.ralaivola@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN16625">
    <nom>SELLAMI Sana</nom>
    <mail>sana.sellami@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN17708">
    <nom>MICHEL Stephane</nom>
    <mail/>
  </intervenant>
  <intervenant id="IN18">
    <nom>MASSAT Jean Luc</nom>
    <mail>jean-luc.massat@univ-amu.fr</mail>
    <siteWeb>http://jean-luc.massat.perso.luminy.univ-amu.fr</siteWeb>
    <infoComplementaire typeInfo="Taille">1m80</infoComplementaire>
    <infoComplementaire typeInfo="Gentil">Oui</infoComplementaire>
  </intervenant>
  <intervenant id="IN2563">
    <nom>GODARD Emmanuel</nom>
    <mail>emmanuel.godard@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN3524">
    <nom>LUGIEZ Denis</nom>
    <mail>denis.lugiez@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN616">
    <nom>AGOPIAN Roland</nom>
    <mail>roland.agopian@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN6213">
    <nom>LABOUREL Arnaud</nom>
    <mail>arnaud.labourel@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN7001">
    <nom>CREIGNOU Nadia</nom>
    <mail>nadia.creignou@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN7680">
    <nom>LAI Claude</nom>
    <mail>claude.lai@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN7722">
    <nom>NOVELLI Noel</nom>
    <mail>noel.novelli@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN7931">
    <nom>RISCH Sylvie</nom>
    <mail>sylvie.risch@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN8006">
    <nom>BOI Jean Marc</nom>
    <mail>jean-marc.boi@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN8086">
    <nom>VAXES Yann</nom>
    <mail>yann.vaxes@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN9224">
    <nom>MORIN Remi</nom>
    <mail>remi.morin@univ-amu.fr</mail>
  </intervenant>
  <intervenant id="IN9941">
    <nom>BECHET Frederic</nom>
    <mail>frederic.bechet@univ-amu.fr</mail>
  </intervenant>
  <UE id="ENSINAU1">
    <nom>Génie Logiciel</nom>
    <ref-intervenant ref="IN7722"/>
    <nbCreditsUE>6</nbCreditsUE>
    <résumé>
      <p>
				<t>- Processus logiciel</t>
				<br/>
				<t>- Gestion de projet</t>
				<br/>
				<t>- Spécification et conception (artefact : notation UML)</t>
				<br/>
				<t>- Design patterns</t>
			</p>
    </résumé>
    <lieu_d_enseignement><Luminy/></lieu_d_enseignement>
  </UE>
  <UE id="ENSINAU10">
    <nom>Modèles à évènements discrets</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé>
      <p>
				<t>Posséder les notions de base en modélisation et analyse de
					systèmes dynamiques à événements discrets et particulièrement
					appréhender le formalisme réseau de</t>
				<br/>
				<t>Pétri. Étudier la conception et la spécification des systèmes
					réactifs à travers l'analyse du modèle à évènements discrets
					(concurrence, parallélisme, synchronisation).</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINAU11">
    <nom>Introduction à l'apprentissage automatique</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé>
      <p>
				<t>- Introduction aux concepts de bases : formalisme statistique,
					erreur de généralisation</t>
				<br/>
				<t>- Arbres de décision : algorithme ID3, élagage, programmation</t>
				<br/>
				<t>- Algorithme du perceptron : algorithme, temps de convergence,
					propriétés de généralisation, application à la classification de
					textes</t>
				<br/>
				<t>- Régression logistique : cadre probabiliste, maximisation de la
					vraisemblance, optimisation par gradient conjugué et méthode de
					Newton, application à la classification de textes</t>
				<br/>
				<t>- Quelques éléments théoriques : notion de capacité de classes de
					fonctions, complexité de Rademacher, borne dépendante des données.</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINAU2">
    <nom>Complexité</nom>
    <ref-intervenant ref="IN7001"/>
    <ref-intervenant ref="IN13794"/>
    <nbCreditsUE>6</nbCreditsUE>
    <résumé>
      <p>
				<t>- Rappels sur les notions d'analyse de la complexité des
					algorithmes et des problèmes.</t>
				<br/>
				<t>- Notion de problèmes (décision, recherche, dénombrement,
					énumération, optimisation). Bornes inférieures de complexité.</t>
				<br/>
				<t>- Classes P et NP. Problèmes NP-complets.</t>
				<br/>
				<t>- Méthodes de résolution des problèmes NP-Complets.</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINAU3">
    <nom>Réseaux</nom>
    <nbCreditsUE>6</nbCreditsUE>
    <résumé>
      <p>
				<t>- Architecture en couches, standard OSI</t>
				<br/>
				<t>- Couche physique</t>
				<br/>
				<t>- Couche liaison de Données</t>
				<br/>
				<t>- Réseau IP</t>
				<br/>
				<t>- Algorithmes de routage, routage IP</t>
				<br/>
				<t>- Protocole TCP/IP</t>
				<br/>
				<t>- Couche Application : HTTP, SMTP, FTP, ...</t>
				<br/>
				<t>- Bases des protocoles cryptographiques (terminologie,
					architecture à clef publique).</t>
				<br/>
				<t>- Introduction à la Sécurité des réseaux.</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINAU4">
    <nom>Programmation fonctionnelle</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé>
      <p>
				<t>1- Introduction à la programmation fonctionnelle, sur l'exemple
					du langage</t>
				<br/>
				<t>OCaml</t>
				<br/>
				<t>Expressions, évaluation, types de base. Polymorphisme, ordre
					supérieur.</t>
				<br/>
				<t>Fonctions récursives, filtrage. Les diverses stratégies
					d'évaluation, application à la programmation d'un opérateur de
					point fixe.</t>
				<br/>
				<t>2- Les types</t>
				<br/>
				<t>Sommes, types récursifs, polymorphes. Arbres. Filtrage.</t>
				<br/>
				<t>3- Sémantique opérationnelle</t>
				<br/>
				<t>Liaisons, environnements, clôtures. Évaluation des fonctions
					récursives .</t>
				<br/>
				<t>4- Aspects impératifs</t>
				<br/>
				<t>Exceptions, entrées-sorties, séquencement, fichiers, références,
					tableaux, enregistrements.</t>
				<br/>
				<t>5- Implantation du filtrage en OCaml</t>
				<br/>
				<t>Termes formels, substitutions, filtrage.</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINAU5">
    <nom>Programmation parallèle</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé>
      <p>
				<t>Ma position est que dans programmation parallèle, on fait de la
					programmation multithread en JAVA, en tâchant d'être rigoureux :
					présentation des problèmes et des solutions algorithmiques ;
					classes utiles ; construction de classe threadsafe ; détail de
					modèle mémoire</t>
				<br/>
				<t>Java et garantie DRF.</t>
				<br/>
				<t>Cette année j'ai ajouté vérification formelle d'algorithmes
					parallèles (ou distribués).</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINAU6">
    <nom>Programmation logique</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé>
      <p>
				<t>- Introduction. Forme générale des règles. Effacement,
					unification, backtracking. Contrôle de l'exécution.</t>
				<br/>
				<t>- Listes, arbres et n-uplets. Liste représentée par différence de
					listes. Ajout en tête et en queue, concaténation.</t>
				<br/>
				<t>- Analyseurs syntaxiques. Construction d'un arbre syntaxique.
					Liste des feuilles d'un arbre. Freeze et analyse par feuille.</t>
				<br/>
				<t>- Règles prédéfinies.</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINAU7">
    <nom>Outils de l'internet</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé>
      <p>
				<t>- Présentation d'Internet.</t>
				<br/>
				<t>- Les langages et les normes sur Internet.</t>
				<br/>
				<t>- Les protocoles : HTTP, HTTP, SMTP, IMAP, POP3</t>
				<br/>
				<t>- Les applications web.</t>
				<br/>
				<t>- Sécurité.</t>
				<br/>
				<t>- Les nouvelles et futures technologies.</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINAU8">
    <nom>Système embarqué</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé/>
  </UE>
  <UE id="ENSINAU9">
    <nom>Fondamentaux pour l'ingénierie des langues</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé>
      <p>
				<t>- Rappel de théorie des langages</t>
				<br/>
				<t>- Algorithmes d'analyse syntaxique pour grammaires ambiguës</t>
				<br/>
				<t>- Transducteurs finis et leur application en TAL</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINBU1">
    <nom>Anglais</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé>
      <p>
				<t>Un enseignement destiné à confirmer l'utilisation de l'anglais
					dans le contexte de l'informatique ainsi que dans la pratique
					professionnelle.</t>
			</p>
    </résumé>
  </UE>
  <UE id="ENSINBU10">
    <nom>Intégration des systèmes d'information</nom>
    <nbCreditsUE>3</nbCreditsUE>
    <résumé>
      <p>
