=== txss/XML_Project/tp3.dtd
<?xml version="1.0" encoding="UTF-8" ?>


<!ELEMENT master           			(intervenant+,parcours,parcours)>

<!ENTITY % lum "Luminy">
<!ENTITY % jer "St-Jerôme">
<!ENTITY % éto "étoile">

<!ENTITY  dom.univ    "univ-amu.fr" >
<!ENTITY  dom.dil     "dil.&dom.univ;" >



<!ELEMENT UE						(nomUE,ref-intervenant+,nbCreditsUE,résumé?, plan?, lieu_d_enseignement+)>
<!ATTLIST UE
    id ID #REQUIRED
    >
    
<!ELEMENT nomUE           			(#PCDATA)>
<!ELEMENT ref-intervenant			EMPTY    >
<!ATTLIST ref-intervenant
    ref IDREF #REQUIRED
    >
<!ELEMENT nbCreditsUE     			(#PCDATA)>
<!ELEMENT résumé        			(p)*>
<!ELEMENT plan          			(p)*>
<!ELEMENT lieu_d_enseignement    	(%lum;|%jer;|%éto;)>

<!ELEMENT p 						(#PCDATA|b|i|tt|p|ul|table|a)*>
<!ELEMENT ul				    	(p)+>
<!ELEMENT table						(tr)+>
<!ELEMENT tr						(td)+>
<!ELEMENT b							(#PCDATA)>
<!ELEMENT i							(#PCDATA)>
<!ELEMENT tt						(#PCDATA)>
<!ELEMENT a					    	(#PCDATA)>

<!ELEMENT intervenant				(nomIntervenant,mail,siteWeb?)>
<!ATTLIST intervenant
    id ID #REQUIRED
    >
    
<!ELEMENT nomIntervenant           	(#PCDATA)>
<!ELEMENT mail          			(#PCDATA)>
<!ELEMENT siteWeb        			(#PCDATA)>

<!ELEMENT semestre					(bloc-UE+)>

<!ELEMENT bloc-UE                   (nbCreditsBloc,UE+)>
<!ATTLIST bloc-UE
    rôle (Obligatoire|Facultatif) #REQUIRED
    >
<!ELEMENT nbCreditsBloc         	(#PCDATA)>


<!ELEMENT parcours                  (reponsable, nomParcours, description, débouché*,semestre,semestre)>
<!ELEMENT reponsable                (#PCDATA)>
<!ELEMENT nomParcours               (#PCDATA)>
<!ELEMENT description               (p)*>
<!ELEMENT débouché	                (p)*>

=== txss/XML_Project/tp3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE master SYSTEM "tp3.dtd">

<master>
   <intervenant id="massat">
      <nomIntervenant>Jean-Luc Massat</nomIntervenant>
      <mail>jean-luc.massat@&dom.univ;</mail>
      <siteWeb>http://jean-luc.massat.perso.luminy.&dom.univ;</siteWeb>
   </intervenant>
   <intervenant id="reynier">
      <nomIntervenant>Pierre-Alain Reynier</nomIntervenant>
      <mail>pierre-alain.reynier@&dom.univ;</mail>
   </intervenant>
   <intervenant id="ollagnier">
      <nomIntervenant>Anaïs Ollagnier</nomIntervenant>
      <mail>anais.ollagnier@&dom.univ;</mail>
   </intervenant>
   <intervenant id="perrot">
      <nomIntervenant>Kevin Perrot</nomIntervenant>
      <mail>kevin.perrot@&dom.univ;</mail>
   </intervenant>
   <intervenant id="arrighi">
      <nomIntervenant>Pablo Arrighi</nomIntervenant>
      <mail>pablo.arrighi@&dom.univ;</mail>
   </intervenant>
   <intervenant id="olive">
      <nomIntervenant>Frédéric Olive</nomIntervenant>
      <mail>frederic.olive@&dom.univ;</mail>
   </intervenant>
   <intervenant id="creignou">
      <nomIntervenant>Nadia Creignou</nomIntervenant>
      <mail>nadia.creignou@&dom.univ;</mail>
   </intervenant>
   <intervenant id="godard">
      <nomIntervenant>Emmanuel Godard</nomIntervenant>
      <mail>emmanuel.godard@&dom.univ;</mail>
   </intervenant>
    <intervenant id="tichit">
      <nomIntervenant>Laurent Tichit</nomIntervenant>
      <mail>laurent.tichit@&dom.univ;</mail>
   </intervenant>
    <intervenant id="santocanal">
      <nomIntervenant>Luigi santocanal</nomIntervenant>
      <mail>luigi.santocanal@&dom.univ;</mail>
   </intervenant>
    <intervenant id="couetoux">
      <nomIntervenant>Basile Couetoux</nomIntervenant>
      <mail>basile.couetoux@&dom.univ;</mail>
   </intervenant>
    <intervenant id="novelli">
      <nomIntervenant>Noël Novelli</nomIntervenant>
      <mail>noel.novelli@&dom.univ;</mail>
   </intervenant>
  
   <UE id="ENSINAU1">
  	<nomUE>Génie Logiciel</nomUE>
   	<ref-intervenant ref="perrot" />
   	<ref-intervenant ref="arrighi" />
   	<nbCreditsUE>6</nbCreditsUE>
   	<lieu_d_enseignement>Luminy</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
 <UE id="ENSINBU20">
  	<nomUE>Complexité</nomUE>
   	<ref-intervenant ref="olive" />
   	<ref-intervenant ref="creignou" />
   	<ref-intervenant ref="perrot" />
   	<nbCreditsUE>6</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
 <UE id="ENSINBU3">
   	<nomUE>Réseaux</nomUE>
   	<ref-intervenant ref="godard" />
   	<ref-intervenant ref="tichit" />
   	<nbCreditsUE>6</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU40">
   	<nomUE>Programmation fonctionnelle</nomUE>
   	<ref-intervenant ref="santocanal" />
   	<ref-intervenant ref="couetoux" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU5">
   	<nomUE>BDR : approfondissement</nomUE>
   	<ref-intervenant ref="novelli" />
   	<ref-intervenant ref="sabatier" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU6">
   	<nomUE>Programmation logique</nomUE>
   	<ref-intervenant ref="stefanini" />
   	<ref-intervenant ref="godebert" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU70">
   	<nomUE>Outils de l'internet</nomUE>
   	<ref-intervenant ref="contensin" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU8">
   	<nomUE>Système embarqué</nomUE>
   	<ref-intervenant ref="niebert" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU90">
   	<nomUE>Fondamentaux pour l'ingénierie des langues </nomUE>
   	<ref-intervenant ref="bechet" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU100">
   	<nomUE>Modèles à évènements discrets</nomUE>
   	<ref-intervenant ref="BOUCELMA" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINAU13">
   	<nomUE>Pratique de la cryptographie</nomUE>
   	<ref-intervenant ref="morin" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU1">
   	<nomUE>Anglais</nomUE>
   	<ref-intervenant ref="dalmolin" />
   	<ref-intervenant ref="desbordes" />
   	<ref-intervenant ref="grainger" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU2">
   	<nomUE>Communication</nomUE>
   	<ref-intervenant ref="rene" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement> &lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  <UE id="ENSINBU4">
   	<nomUE>XML</nomUE>
   	<ref-intervenant ref="massat" />
   	<ref-intervenant ref="reynier" />
   	<ref-intervenant ref="ollagnier" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
  </UE>
  
  <UE id="ENSINBU50">
  	<nomUE>ARO</nomUE>
   	<ref-intervenant ref="cepoi" />
   	<ref-intervenant ref="couetoux" />
   	<ref-intervenant ref="naves" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
 <UE id="ENSINBU15">
  	<nomUE>Programmation Parallèle</nomUE>
   	<ref-intervenant ref="morin" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
 <UE id="ENSINBU60">
  	<nomUE>Projet</nomUE>
   	<ref-intervenant ref="jegou" />
   	<nbCreditsUE>6</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE> 
  <UE id="ENSINBU7">
  	<nomUE>Stage de deux mois</nomUE>
   	<ref-intervenant ref="jegou" />
   	<nbCreditsUE>6</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
  <UE id="ENSINBU9">
  	<nomUE>Algorithme distribué</nomUE>
   	<ref-intervenant ref="das" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
  <UE id="ENSINBU10">
  	<nomUE>Intégration des systèmes d'information</nomUE>
   	<ref-intervenant ref="boucelma" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
  <UE id="ENSINBU11">
  	<nomUE>Initiation à la fouille de données et à l'optimisation des SGBD</nomUE>
   	<ref-intervenant ref="novelli" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
  <UE id="ENSINBU12">
  	<nomUE>Intelligence artificielle</nomUE>
   	<ref-intervenant ref="risch" />
   	<ref-intervenant ref="benhamou" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
  <UE id="ENSINBU13">
  	<nomUE>Algorithme à performance garantie</nomUE>
   	<ref-intervenant ref="couetoux" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
  <UE id="ENSINBU14">
  	<nomUE>Introduction à l'apprentissage automatique</nomUE>
   	<ref-intervenant ref="kadri" />
   	<nbCreditsUE>3</nbCreditsUE>
   	<lieu_d_enseignement>&lum;</lieu_d_enseignement>
   	<lieu_d_enseignement>&jer;</lieu_d_enseignement>
 </UE>
   
   <parcours>
     <responsable>Jean-Luc Massat</responsable>
     <nomParcours>Master1</nomParcours>
     <description>
     	<p>Nothing to say</p>
     </description>
     <débouché>
     	<p>On <b>espère</b> </p>
     </débouché>
     <semestre>
     	<bloc-UE rôle="Obligatoire">
     		<nbCreditsBloc>6</nbCreditsBloc>
     		<refUE refUE="ENSINBU4" />
     	</bloc-UE>
     </semestre>
     <semestre>
       	<bloc-UE rôle="Obligatoire">
  			<nbCreditsBloc>6</nbCreditsBloc>
  			<refUE refUE="ENSINBU5" />
  		</bloc-UE>
     </semestre>
   </parcours>
   
   <parcours>
   		<responsable>Morin </responsable>
   		<nomParcours> Master 2 </nomParcours>
   		<description><p>nothing</p></description>
   		<semestre>
   			<bloc-UE rôle="Obligatoire">
	  			<nbCreditsBloc>18</nbCreditsBloc>
	  			<refUE refUE="ENSINBU5" />
  			</bloc-UE>
   		</semestre>
   		<semestre>
   			<bloc-UE rôle="Obligatoire">
	  			<nbCreditsBloc>12</nbCreditsBloc>
	  			<refUE refUE="ENSINBU5" />
	  			<refUE refUE="ENSINBU11" />
	  			<refUE refUE="ENSINBU2" />
	  			<refUE refUE="ENSINBU1" />
  			</bloc-UE>
   		</semestre>
   </parcours>
  
</master>
